[project]
name = "cholerny-impedant"
version = "0.1.0"
description = "Próba pomocy impedantowi"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "impedance>=1.7.1",
    "jupyter>=1.1.1",
    "pandas>=2.3.2",
    "pyqt6>=6.9.1",
    "schemdraw>=0.21",
]
